module.exports = {
	"data":[
				{
					"articleTypeId":6852,
					"articleTypeName":"全年资料",
					"lotteryType":2
				},
				{
					"articleTypeId":7352,
					"articleTypeName":"文字资料",
					"lotteryType":2
				},
				{
					"articleTypeId":7602,
					"articleTypeName":"波肖尾门报",
					"lotteryType":2
				},
				{
					"articleTypeId":7412,
					"articleTypeName":"通天报解码",
					"lotteryType":2
				},
				{
					"articleTypeId":7762,
					"articleTypeName":"六合家宝A",
					"lotteryType":2
				},
				{
					"articleTypeId":7572,
					"articleTypeName":"白小姐会员",
					"lotteryType":2
				},
				{
					"articleTypeId":7382,
					"articleTypeName":"30码中特图",
					"lotteryType":2
				},
				{
					"articleTypeId":7732,
					"articleTypeName":"彩霸王六肖",
					"lotteryType":2
				},
				{
					"articleTypeId":7542,
					"articleTypeName":"36码中特图",
					"lotteryType":2
				},
				{
					"articleTypeId":7942,
					"articleTypeName":"一句真言图",
					"lotteryType":2
				},
				{
					"articleTypeId":7342,
					"articleTypeName":"新生活幽默",
					"lotteryType":2
				},
				{
					"articleTypeId":7702,
					"articleTypeName":"澳话中有意",
					"lotteryType":2
				},
				{
					"articleTypeId":7512,
					"articleTypeName":"腾算策略报",
					"lotteryType":2
				},
				{
					"articleTypeId":7902,
					"articleTypeName":"新图库禁肖",
					"lotteryType":2
				},
				{
					"articleTypeId":6832,
					"articleTypeName":"生肖属性",
					"lotteryType":2
				},
				{
					"articleTypeId":6892,
					"articleTypeName":"奇觉四象",
					"lotteryType":2
				},
				{
					"articleTypeId":7672,
					"articleTypeName":"管家婆密传",
					"lotteryType":2
				},
				{
					"articleTypeId":7482,
					"articleTypeName":"看图抓码图",
					"lotteryType":2
				},
				{
					"articleTypeId":7842,
					"articleTypeName":"七肖中特报",
					"lotteryType":2
				},
				{
					"articleTypeId":7872,
					"articleTypeName":"三八婆密报",
					"lotteryType":2
				},
				{
					"articleTypeId":7982,
					"articleTypeName":"澳门天线宝",
					"lotteryType":2
				},
				{
					"articleTypeId":8354,
					"articleTypeName":"各坛好料",
					"lotteryType":2
				},
				{
					"articleTypeId":7792,
					"articleTypeName":"内部传真报",
					"lotteryType":2
				},
				{
					"articleTypeId":7642,
					"articleTypeName":"二尾四码图",
					"lotteryType":2
				},
				{
					"articleTypeId":7452,
					"articleTypeName":"凤凰卜封图",
					"lotteryType":2
				},
				{
					"articleTypeId":7812,
					"articleTypeName":"内幕特肖A",
					"lotteryType":2
				},
				{
					"articleTypeId":7612,
					"articleTypeName":"传真八点料",
					"lotteryType":2
				},
				{
					"articleTypeId":7422,
					"articleTypeName":"澳门老人报",
					"lotteryType":2
				},
				{
					"articleTypeId":7772,
					"articleTypeName":"六合家宝B",
					"lotteryType":2
				},
				{
					"articleTypeId":7582,
					"articleTypeName":"白小姐密报",
					"lotteryType":2
				},
				{
					"articleTypeId":7392,
					"articleTypeName":"澳门孩童报",
					"lotteryType":2
				},
				{
					"articleTypeId":7742,
					"articleTypeName":"六合简报图",
					"lotteryType":2
				},
				{
					"articleTypeId":7952,
					"articleTypeName":"澳门一样发",
					"lotteryType":2
				},
				{
					"articleTypeId":6862,
					"articleTypeName":"高手解特",
					"lotteryType":2
				},
				{
					"articleTypeId":7362,
					"articleTypeName":"平特一肖图",
					"lotteryType":2
				},
				{
					"articleTypeId":7712,
					"articleTypeName":"劲爆龙虎榜",
					"lotteryType":2
				},
				{
					"articleTypeId":7522,
					"articleTypeName":"澳门蛇蛋图",
					"lotteryType":2
				},
				{
					"articleTypeId":7922,
					"articleTypeName":"无敌猪哥报",
					"lotteryType":2
				},
				{
					"articleTypeId":6842,
					"articleTypeName":"高手预测",
					"lotteryType":2
				},
				{
					"articleTypeId":5202,
					"articleTypeName":"天天好彩",
					"lotteryType":2
				},
				{
					"articleTypeId":7682,
					"articleTypeName":"马会火烧图",
					"lotteryType":2
				},
				{
					"articleTypeId":7492,
					"articleTypeName":"东成西就图",
					"lotteryType":2
				},
				{
					"articleTypeId":7852,
					"articleTypeName":"博彩平特报",
					"lotteryType":2
				},
				{
					"articleTypeId":7882,
					"articleTypeName":"三怪禁肖图",
					"lotteryType":2
				},
				{
					"articleTypeId":7992,
					"articleTypeName":"公式规律",
					"lotteryType":2
				},
				{
					"articleTypeId":7822,
					"articleTypeName":"内幕特肖B",
					"lotteryType":2
				},
				{
					"articleTypeId":7912,
					"articleTypeName":"特码快递报",
					"lotteryType":2
				},
				{
					"articleTypeId":7652,
					"articleTypeName":"凤姐30码图",
					"lotteryType":2
				},
				{
					"articleTypeId":7462,
					"articleTypeName":"12码中特图",
					"lotteryType":2
				},
				{
					"articleTypeId":7552,
					"articleTypeName":"庄家吃码图",
					"lotteryType":2
				},
				{
					"articleTypeId":7622,
					"articleTypeName":"澳门大陆报",
					"lotteryType":2
				},
				{
					"articleTypeId":7432,
					"articleTypeName":"财神玄机报",
					"lotteryType":2
				},
				{
					"articleTypeId":7782,
					"articleTypeName":"梦儿数码报",
					"lotteryType":2
				},
				{
					"articleTypeId":7592,
					"articleTypeName":"波肖一波中",
					"lotteryType":2
				},
				{
					"articleTypeId":7402,
					"articleTypeName":"一字解特码",
					"lotteryType":2
				},
				{
					"articleTypeId":7752,
					"articleTypeName":"六合英雄报",
					"lotteryType":2
				},
				{
					"articleTypeId":7962,
					"articleTypeName":"曾道人暗语",
					"lotteryType":2
				},
				{
					"articleTypeId":6882,
					"articleTypeName":"澳门挂牌",
					"lotteryType":2
				},
				{
					"articleTypeId":7372,
					"articleTypeName":"正版射牌图",
					"lotteryType":2
				},
				{
					"articleTypeId":7722,
					"articleTypeName":"狼女侠客图",
					"lotteryType":2
				},
				{
					"articleTypeId":7532,
					"articleTypeName":"周公玄机报",
					"lotteryType":2
				},
				{
					"articleTypeId":7932,
					"articleTypeName":"鱼跃龙门报",
					"lotteryType":2
				},
				{
					"articleTypeId":7692,
					"articleTypeName":"红姐内幕图",
					"lotteryType":2
				},
				{
					"articleTypeId":7502,
					"articleTypeName":"白小姐救世",
					"lotteryType":2
				},
				{
					"articleTypeId":7892,
					"articleTypeName":"正版通天报",
					"lotteryType":2
				},
				{
					"articleTypeId":6822,
					"articleTypeName":"内部猛料",
					"lotteryType":2
				},
				{
					"articleTypeId":7832,
					"articleTypeName":"千手观音图",
					"lotteryType":2
				},
				{
					"articleTypeId":7862,
					"articleTypeName":"神童透码报",
					"lotteryType":2
				},
				{
					"articleTypeId":7972,
					"articleTypeName":"澳门抓码王",
					"lotteryType":2
				},
				{
					"articleTypeId":7662,
					"articleTypeName":"发财波局报",
					"lotteryType":2
				},
				{
					"articleTypeId":7472,
					"articleTypeName":"值日生肖图",
					"lotteryType":2
				},
				{
					"articleTypeId":7562,
					"articleTypeName":"澳门男人味",
					"lotteryType":2
				},
				{
					"articleTypeId":7632,
					"articleTypeName":"澳门大陆仔",
					"lotteryType":2
				},
				{
					"articleTypeId":7442,
					"articleTypeName":"澳门签牌图",
					"lotteryType":2
				},
				{
					"articleTypeId":7802,
					"articleTypeName":"澳门牛头报",
					"lotteryType":2
				},
				{
					"articleTypeId":5212,
					"articleTypeName":"澳门七星图",
					"lotteryType":2
				},
				{
					"articleTypeId":5222,
					"articleTypeName":"澳门跑马图",
					"lotteryType":2
				},
				{
					"articleTypeId":5232,
					"articleTypeName":"澳门不夜城",
					"lotteryType":2
				},
				{
					"articleTypeId":5242,
					"articleTypeName":"八仙过海图",
					"lotteryType":2
				},
				{
					"articleTypeId":5252,
					"articleTypeName":"八仙指路图",
					"lotteryType":2
				},
				{
					"articleTypeId":5262,
					"articleTypeName":"财神报料图",
					"lotteryType":2
				},
				{
					"articleTypeId":5272,
					"articleTypeName":"单双中特图",
					"lotteryType":2
				},
				{
					"articleTypeId":5282,
					"articleTypeName":"赌王心水图",
					"lotteryType":2
				},
				{
					"articleTypeId":5292,
					"articleTypeName":"佛祖禁肖图",
					"lotteryType":2
				},
				{
					"articleTypeId":5302,
					"articleTypeName":"凤凰天机图",
					"lotteryType":2
				},
				{
					"articleTypeId":5312,
					"articleTypeName":"新管家婆图",
					"lotteryType":2
				},
				{
					"articleTypeId":5322,
					"articleTypeName":"新挂牌彩图",
					"lotteryType":2
				},
				{
					"articleTypeId":5332,
					"articleTypeName":"观音彩码报",
					"lotteryType":2
				},
				{
					"articleTypeId":5342,
					"articleTypeName":"挂牌平特报",
					"lotteryType":2
				},
				{
					"articleTypeId":5352,
					"articleTypeName":"功夫早茶图",
					"lotteryType":2
				},
				{
					"articleTypeId":5362,
					"articleTypeName":"鬼谷子爆肖",
					"lotteryType":2
				},
				{
					"articleTypeId":5372,
					"articleTypeName":"澳门红虎图",
					"lotteryType":2
				},
				{
					"articleTypeId":5382,
					"articleTypeName":"皇道吉日图",
					"lotteryType":2
				},
				{
					"articleTypeId":5392,
					"articleTypeName":"澳幽默猜测",
					"lotteryType":2
				},
				{
					"articleTypeId":5402,
					"articleTypeName":"济公有真言",
					"lotteryType":2
				},
				{
					"articleTypeId":5412,
					"articleTypeName":"今日闲情２",
					"lotteryType":2
				},
				{
					"articleTypeId":5422,
					"articleTypeName":"金多宝传真",
					"lotteryType":2
				},
				{
					"articleTypeId":5432,
					"articleTypeName":"今日闲情１",
					"lotteryType":2
				},
				{
					"articleTypeId":5442,
					"articleTypeName":"金钱豹功夫",
					"lotteryType":2
				},
				{
					"articleTypeId":5452,
					"articleTypeName":"开心果先锋",
					"lotteryType":2
				},
				{
					"articleTypeId":5462,
					"articleTypeName":"看图解特码",
					"lotteryType":2
				},
				{
					"articleTypeId":5472,
					"articleTypeName":"四组三连肖",
					"lotteryType":2
				},
				{
					"articleTypeId":5482,
					"articleTypeName":"澳门两肖特",
					"lotteryType":2
				},
				{
					"articleTypeId":5492,
					"articleTypeName":"澳六合头条",
					"lotteryType":2
				},
				{
					"articleTypeId":5502,
					"articleTypeName":"另版跑狗图",
					"lotteryType":2
				},
				{
					"articleTypeId":5512,
					"articleTypeName":"老版跑狗图",
					"lotteryType":2
				},
				{
					"articleTypeId":5522,
					"articleTypeName":"澳门传真图",
					"lotteryType":2
				},
				{
					"articleTypeId":5532,
					"articleTypeName":"澳门猛虎报",
					"lotteryType":2
				},
				{
					"articleTypeId":5542,
					"articleTypeName":"澳门码头诗",
					"lotteryType":2
				},
				{
					"articleTypeId":5552,
					"articleTypeName":"每日闲情图",
					"lotteryType":2
				},
				{
					"articleTypeId":5562,
					"articleTypeName":"澳门女人味",
					"lotteryType":2
				},
				{
					"articleTypeId":5572,
					"articleTypeName":"内幕传真图",
					"lotteryType":2
				},
				{
					"articleTypeId":5582,
					"articleTypeName":"澳门女财神",
					"lotteryType":2
				},
				{
					"articleTypeId":5592,
					"articleTypeName":"澳门青龙报",
					"lotteryType":2
				},
				{
					"articleTypeId":5602,
					"articleTypeName":"新趣味幽默",
					"lotteryType":2
				},
				{
					"articleTypeId":5612,
					"articleTypeName":"澳门四不像",
					"lotteryType":2
				},
				{
					"articleTypeId":5622,
					"articleTypeName":"神奇八卦图",
					"lotteryType":2
				},
				{
					"articleTypeId":5632,
					"articleTypeName":"四不像玄机",
					"lotteryType":2
				},
				{
					"articleTypeId":5642,
					"articleTypeName":"六麒麟透码",
					"lotteryType":2
				},
				{
					"articleTypeId":5652,
					"articleTypeName":"新特码诗句",
					"lotteryType":2
				},
				{
					"articleTypeId":5662,
					"articleTypeName":"铁板神算图",
					"lotteryType":2
				},
				{
					"articleTypeId":5672,
					"articleTypeName":"澳门玄机图",
					"lotteryType":2
				},
				{
					"articleTypeId":5682,
					"articleTypeName":"小黄人幽默",
					"lotteryType":2
				},
				{
					"articleTypeId":5692,
					"articleTypeName":"玄机妙语图",
					"lotteryType":2
				},
				{
					"articleTypeId":5702,
					"articleTypeName":"澳门熊出没",
					"lotteryType":2
				},
				{
					"articleTypeId":5712,
					"articleTypeName":"小龙女料",
					"lotteryType":2
				},
				{
					"articleTypeId":5722,
					"articleTypeName":"马会绝杀",
					"lotteryType":2
				},
				{
					"articleTypeId":5732,
					"articleTypeName":"金多宝网",
					"lotteryType":2
				},
				{
					"articleTypeId":5742,
					"articleTypeName":"彩图诗句",
					"lotteryType":2
				},
				{
					"articleTypeId":5752,
					"articleTypeName":"鬼谷子网",
					"lotteryType":2
				},
				{
					"articleTypeId":5762,
					"articleTypeName":"报刊大全",
					"lotteryType":2
				},
				{
					"articleTypeId":5772,
					"articleTypeName":"管家婆料",
					"lotteryType":2
				},
				{
					"articleTypeId":5782,
					"articleTypeName":"曾道原创",
					"lotteryType":2
				},
				{
					"articleTypeId":5792,
					"articleTypeName":"白姐最准",
					"lotteryType":2
				},
				{
					"articleTypeId":5802,
					"articleTypeName":"赛马会料",
					"lotteryType":2
				},
				{
					"articleTypeId":5812,
					"articleTypeName":"本站推荐",
					"lotteryType":2
				},
				{
					"articleTypeId":5822,
					"articleTypeName":"九龙内幕",
					"lotteryType":2
				},
				{
					"articleTypeId":5832,
					"articleTypeName":"白姐讯息",
					"lotteryType":2
				},
				{
					"articleTypeId":5842,
					"articleTypeName":"曾氏集团",
					"lotteryType":2
				},
				{
					"articleTypeId":5852,
					"articleTypeName":"正版资料",
					"lotteryType":2
				},
				{
					"articleTypeId":5862,
					"articleTypeName":"权威资料",
					"lotteryType":2
				},
				{
					"articleTypeId":5872,
					"articleTypeName":"跑马玄机",
					"lotteryType":2
				},
				{
					"articleTypeId":5882,
					"articleTypeName":"六合玄机",
					"lotteryType":2
				},
				{
					"articleTypeId":5892,
					"articleTypeName":"精版资料",
					"lotteryType":2
				},
				{
					"articleTypeId":5902,
					"articleTypeName":"独家赢钱",
					"lotteryType":2
				},
				{
					"articleTypeId":5912,
					"articleTypeName":"天下彩料",
					"lotteryType":2
				},
				{
					"articleTypeId":5922,
					"articleTypeName":"马会贴士",
					"lotteryType":2
				},
				{
					"articleTypeId":5932,
					"articleTypeName":"财运童子",
					"lotteryType":2
				},
				{
					"articleTypeId":5942,
					"articleTypeName":"精准高手",
					"lotteryType":2
				},
				{
					"articleTypeId":5952,
					"articleTypeName":"铁算盘料",
					"lotteryType":2
				},
				{
					"articleTypeId":5962,
					"articleTypeName":"神码再现",
					"lotteryType":2
				},
				{
					"articleTypeId":5972,
					"articleTypeName":"仙人指路",
					"lotteryType":2
				},
				{
					"articleTypeId":5982,
					"articleTypeName":"六合寶典",
					"lotteryType":2
				},
				{
					"articleTypeId":5992,
					"articleTypeName":"心水玄机",
					"lotteryType":2
				},
				{
					"articleTypeId":6002,
					"articleTypeName":"水果高手",
					"lotteryType":2
				},
				{
					"articleTypeId":6012,
					"articleTypeName":"创富好料",
					"lotteryType":2
				},
				{
					"articleTypeId":6022,
					"articleTypeName":"发财精料",
					"lotteryType":2
				},
				{
					"articleTypeId":6032,
					"articleTypeName":"旺角好料",
					"lotteryType":2
				},
				{
					"articleTypeId":6042,
					"articleTypeName":"高手猛料",
					"lotteryType":2
				},
				{
					"articleTypeId":6052,
					"articleTypeName":"平肖平码",
					"lotteryType":2
				},
				{
					"articleTypeId":6062,
					"articleTypeName":"惠泽社群",
					"lotteryType":2
				},
				{
					"articleTypeId":6072,
					"articleTypeName":"贵宾准料",
					"lotteryType":2
				},
				{
					"articleTypeId":6082,
					"articleTypeName":"天天独家",
					"lotteryType":2
				},
				{
					"articleTypeId":6092,
					"articleTypeName":"天天猛料",
					"lotteryType":2
				},
				{
					"articleTypeId":6102,
					"articleTypeName":"福星金牌",
					"lotteryType":2
				},
				{
					"articleTypeId":6112,
					"articleTypeName":"旺角传真",
					"lotteryType":2
				},
				{
					"articleTypeId":6122,
					"articleTypeName":"皇帝猛料",
					"lotteryType":2
				},
				{
					"articleTypeId":6142,
					"articleTypeName":"西门庆料",
					"lotteryType":2
				},
				{
					"articleTypeId":6152,
					"articleTypeName":"竹影梅花",
					"lotteryType":2
				},
				{
					"articleTypeId":6162,
					"articleTypeName":"富奇秦准",
					"lotteryType":2
				},
				{
					"articleTypeId":6172,
					"articleTypeName":"云楚官人",
					"lotteryType":2
				},
				{
					"articleTypeId":6182,
					"articleTypeName":"㊣点来料",
					"lotteryType":2
				},
				{
					"articleTypeId":6192,
					"articleTypeName":"梅花易数",
					"lotteryType":2
				},
				{
					"articleTypeId":6202,
					"articleTypeName":"返璞归真",
					"lotteryType":2
				},
				{
					"articleTypeId":6212,
					"articleTypeName":"周易神算",
					"lotteryType":2
				},
				{
					"articleTypeId":6222,
					"articleTypeName":"六合财经",
					"lotteryType":2
				},
				{
					"articleTypeId":6232,
					"articleTypeName":"奇门遁甲",
					"lotteryType":2
				},
				{
					"articleTypeId":6242,
					"articleTypeName":"六合神算",
					"lotteryType":2
				},
				{
					"articleTypeId":6252,
					"articleTypeName":"九龙特供",
					"lotteryType":2
				},
				{
					"articleTypeId":6262,
					"articleTypeName":"芙蓉王料",
					"lotteryType":2
				},
				{
					"articleTypeId":6272,
					"articleTypeName":"东方赌圣",
					"lotteryType":2
				},
				{
					"articleTypeId":6282,
					"articleTypeName":"红妹资料",
					"lotteryType":2
				},
				{
					"articleTypeId":6302,
					"articleTypeName":"攻克专家",
					"lotteryType":2
				},
				{
					"articleTypeId":6312,
					"articleTypeName":"招财中特",
					"lotteryType":2
				},
				{
					"articleTypeId":6322,
					"articleTypeName":"惠泽内部",
					"lotteryType":2
				},
				{
					"articleTypeId":6342,
					"articleTypeName":"诸葛内幕",
					"lotteryType":2
				},
				{
					"articleTypeId":6372,
					"articleTypeName":"济公指路",
					"lotteryType":2
				},
				{
					"articleTypeId":6382,
					"articleTypeName":"新世纪料",
					"lotteryType":2
				},
				{
					"articleTypeId":6392,
					"articleTypeName":"公牛猛料",
					"lotteryType":2
				},
				{
					"articleTypeId":6402,
					"articleTypeName":"六合天書",
					"lotteryType":2
				},
				{
					"articleTypeId":6412,
					"articleTypeName":"财神玄机",
					"lotteryType":2
				},
				{
					"articleTypeId":6422,
					"articleTypeName":"生财有道",
					"lotteryType":2
				},
				{
					"articleTypeId":6502,
					"articleTypeName":"刘伯温料",
					"lotteryType":2
				},
				{
					"articleTypeId":6522,
					"articleTypeName":"综合统计",
					"lotteryType":2
				},
				{
					"articleTypeId":6572,
					"articleTypeName":"马会原创",
					"lotteryType":2
				},
				{
					"articleTypeId":6582,
					"articleTypeName":"黄大仙料",
					"lotteryType":2
				},
				{
					"articleTypeId":6622,
					"articleTypeName":"彩票赢家",
					"lotteryType":2
				},
				{
					"articleTypeId":6632,
					"articleTypeName":"满堂红网",
					"lotteryType":2
				},
				{
					"articleTypeId":6652,
					"articleTypeName":"曾女士料",
					"lotteryType":2
				},
				{
					"articleTypeId":6662,
					"articleTypeName":"彩票心水",
					"lotteryType":2
				},
				{
					"articleTypeId":6672,
					"articleTypeName":"精料赌圣",
					"lotteryType":2
				},
				{
					"articleTypeId":6682,
					"articleTypeName":"澳门好彩",
					"lotteryType":2
				},
				{
					"articleTypeId":6712,
					"articleTypeName":"澳门赌圣",
					"lotteryType":2
				},
				{
					"articleTypeId":6722,
					"articleTypeName":"彩券公司",
					"lotteryType":2
				},
				{
					"articleTypeId":8689,
					"articleTypeName":"青龙阁论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8770,
					"articleTypeName":"横财富论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8557,
					"articleTypeName":"六合大亨论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8801,
					"articleTypeName":"平一肖图网",
					"lotteryType":2
				},
				{
					"articleTypeId":8560,
					"articleTypeName":"博彩皇论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8579,
					"articleTypeName":"博彩网",
					"lotteryType":2
				},
				{
					"articleTypeId":8820,
					"articleTypeName":"澳门天机网",
					"lotteryType":2
				},
				{
					"articleTypeId":8703,
					"articleTypeName":"幽默玄机坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8719,
					"articleTypeName":"何仙姑论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8599,
					"articleTypeName":"大赢家论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8541,
					"articleTypeName":"聚彩堂论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8573,
					"articleTypeName":"抓码王论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8817,
					"articleTypeName":"八仙神算网",
					"lotteryType":2
				},
				{
					"articleTypeId":8700,
					"articleTypeName":"一点红论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8716,
					"articleTypeName":"福建打枪客",
					"lotteryType":2
				},
				{
					"articleTypeId":8596,
					"articleTypeName":"六合皇论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8686,
					"articleTypeName":"六合通论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8554,
					"articleTypeName":"管家婆论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8798,
					"articleTypeName":"波叔一波中",
					"lotteryType":2
				},
				{
					"articleTypeId":8570,
					"articleTypeName":"破码网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8814,
					"articleTypeName":"踏雪无痕网",
					"lotteryType":2
				},
				{
					"articleTypeId":8590,
					"articleTypeName":"红双喜论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8697,
					"articleTypeName":"彩民网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8713,
					"articleTypeName":"广东八二站",
					"lotteryType":2
				},
				{
					"articleTypeId":8593,
					"articleTypeName":"满堂红论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8683,
					"articleTypeName":"曾道人论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8551,
					"articleTypeName":"红虎论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8795,
					"articleTypeName":"金钱豹功夫",
					"lotteryType":2
				},
				{
					"articleTypeId":8811,
					"articleTypeName":"图找生肖网",
					"lotteryType":2
				},
				{
					"articleTypeId":8587,
					"articleTypeName":"澳彩资料网",
					"lotteryType":2
				},
				{
					"articleTypeId":8694,
					"articleTypeName":"金钥匙论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8827,
					"articleTypeName":"六合神童网",
					"lotteryType":2
				},
				{
					"articleTypeId":8710,
					"articleTypeName":"刘半仙论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8606,
					"articleTypeName":"王中王论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8548,
					"articleTypeName":"天线宝宝论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8777,
					"articleTypeName":"顶级论坛网",
					"lotteryType":2
				},
				{
					"articleTypeId":8808,
					"articleTypeName":"九点禁一肖",
					"lotteryType":2
				},
				{
					"articleTypeId":8567,
					"articleTypeName":"夜明珠论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8603,
					"articleTypeName":"老奇人论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8545,
					"articleTypeName":"报彩神童论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8774,
					"articleTypeName":"八码论坛网",
					"lotteryType":2
				},
				{
					"articleTypeId":8805,
					"articleTypeName":"猛虎报论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8564,
					"articleTypeName":"挂牌论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8584,
					"articleTypeName":"跑狗论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8824,
					"articleTypeName":"特码诗句网",
					"lotteryType":2
				},
				{
					"articleTypeId":8707,
					"articleTypeName":"姜太公论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8542,
					"articleTypeName":"老鼠报论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8690,
					"articleTypeName":"鬼谷子论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8771,
					"articleTypeName":"名人堂论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8558,
					"articleTypeName":"马经论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8802,
					"articleTypeName":"小纸条论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8561,
					"articleTypeName":"杀料网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8581,
					"articleTypeName":"马会论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8821,
					"articleTypeName":"红财神论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8704,
					"articleTypeName":"广东会论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8720,
					"articleTypeName":"小龙女论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8600,
					"articleTypeName":"状元红论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8799,
					"articleTypeName":"挂牌另版网",
					"lotteryType":2
				},
				{
					"articleTypeId":8577,
					"articleTypeName":"跑马论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8818,
					"articleTypeName":"神算挖呀挖",
					"lotteryType":2
				},
				{
					"articleTypeId":8701,
					"articleTypeName":"西游论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8717,
					"articleTypeName":"澳门资料库",
					"lotteryType":2
				},
				{
					"articleTypeId":8597,
					"articleTypeName":"金光佛论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8687,
					"articleTypeName":"彩民之家坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8555,
					"articleTypeName":"美人鱼论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8571,
					"articleTypeName":"六玄网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8815,
					"articleTypeName":"传真三肖版",
					"lotteryType":2
				},
				{
					"articleTypeId":8698,
					"articleTypeName":"123论坛坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8714,
					"articleTypeName":"澳门蓝月亮",
					"lotteryType":2
				},
				{
					"articleTypeId":8594,
					"articleTypeName":"金吊桶论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8684,
					"articleTypeName":"赛马会论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8552,
					"articleTypeName":"神算子论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8796,
					"articleTypeName":"早茶论码网",
					"lotteryType":2
				},
				{
					"articleTypeId":8588,
					"articleTypeName":"六合宝典论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8695,
					"articleTypeName":"观音救世坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8828,
					"articleTypeName":"看图解特码",
					"lotteryType":2
				},
				{
					"articleTypeId":8711,
					"articleTypeName":"资料研究院",
					"lotteryType":2
				},
				{
					"articleTypeId":8591,
					"articleTypeName":"金手指论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8681,
					"articleTypeName":"全讯网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8549,
					"articleTypeName":"摇钱树论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8778,
					"articleTypeName":"奥利奥论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8809,
					"articleTypeName":"值日生肖网",
					"lotteryType":2
				},
				{
					"articleTypeId":8568,
					"articleTypeName":"澳门中特网",
					"lotteryType":2
				},
				{
					"articleTypeId":8812,
					"articleTypeName":"幽默另版网",
					"lotteryType":2
				},
				{
					"articleTypeId":8708,
					"articleTypeName":"东成西就坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8604,
					"articleTypeName":"金多宝论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8546,
					"articleTypeName":"铁算盘论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8775,
					"articleTypeName":"好运一点通",
					"lotteryType":2
				},
				{
					"articleTypeId":8806,
					"articleTypeName":"两肖四码网",
					"lotteryType":2
				},
				{
					"articleTypeId":8565,
					"articleTypeName":"六合味论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8585,
					"articleTypeName":"东方心经论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8825,
					"articleTypeName":"佛祖禁肖图",
					"lotteryType":2
				},
				{
					"articleTypeId":8601,
					"articleTypeName":"黄大仙论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8543,
					"articleTypeName":"六合头条论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8691,
					"articleTypeName":"天下彩论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8772,
					"articleTypeName":"如意论坛网",
					"lotteryType":2
				},
				{
					"articleTypeId":8803,
					"articleTypeName":"澳门来料网",
					"lotteryType":2
				},
				{
					"articleTypeId":8562,
					"articleTypeName":"凤凰天机论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8582,
					"articleTypeName":"小鱼儿论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8822,
					"articleTypeName":"赌神四肖八",
					"lotteryType":2
				},
				{
					"articleTypeId":8705,
					"articleTypeName":"创富网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8556,
					"articleTypeName":"今日闲情论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8800,
					"articleTypeName":"来料精华网",
					"lotteryType":2
				},
				{
					"articleTypeId":8559,
					"articleTypeName":"红姐论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8578,
					"articleTypeName":"118开奖论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8819,
					"articleTypeName":"新澳门天机",
					"lotteryType":2
				},
				{
					"articleTypeId":8702,
					"articleTypeName":"百晓生论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8718,
					"articleTypeName":"广西二五仔",
					"lotteryType":2
				},
				{
					"articleTypeId":8598,
					"articleTypeName":"金财神论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8688,
					"articleTypeName":"藏宝阁论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8721,
					"articleTypeName":"济公救世坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8572,
					"articleTypeName":"九龙论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8816,
					"articleTypeName":"金猴王论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8699,
					"articleTypeName":"港澳站",
					"lotteryType":2
				},
				{
					"articleTypeId":8715,
					"articleTypeName":"澳百万文字",
					"lotteryType":2
				},
				{
					"articleTypeId":8595,
					"articleTypeName":"六合之家论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8685,
					"articleTypeName":"赢彩吧论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8553,
					"articleTypeName":"彩库网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8797,
					"articleTypeName":"发财图论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8813,
					"articleTypeName":"凌波微步网",
					"lotteryType":2
				},
				{
					"articleTypeId":8589,
					"articleTypeName":"六合彩论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8696,
					"articleTypeName":"淘码论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8829,
					"articleTypeName":"澳门信封网",
					"lotteryType":2
				},
				{
					"articleTypeId":8712,
					"articleTypeName":"广西三八网",
					"lotteryType":2
				},
				{
					"articleTypeId":8592,
					"articleTypeName":"花仙子论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8682,
					"articleTypeName":"彩票通论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8550,
					"articleTypeName":"六合慈善论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8794,
					"articleTypeName":"挂牌宝典网",
					"lotteryType":2
				},
				{
					"articleTypeId":8810,
					"articleTypeName":"幽默猜测网",
					"lotteryType":2
				},
				{
					"articleTypeId":8569,
					"articleTypeName":"港澳公式网",
					"lotteryType":2
				},
				{
					"articleTypeId":8709,
					"articleTypeName":"醉八仙论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8605,
					"articleTypeName":"蛇蛋图论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8547,
					"articleTypeName":"88开奖论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8776,
					"articleTypeName":"通天论坛网",
					"lotteryType":2
				},
				{
					"articleTypeId":8807,
					"articleTypeName":"澳门签牌网",
					"lotteryType":2
				},
				{
					"articleTypeId":8566,
					"articleTypeName":"宝马论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8586,
					"articleTypeName":"玄机网论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8693,
					"articleTypeName":"四不像论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8826,
					"articleTypeName":"绿财神论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8602,
					"articleTypeName":"刘伯温论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8544,
					"articleTypeName":"天天好彩",
					"lotteryType":2
				},
				{
					"articleTypeId":8692,
					"articleTypeName":"惠泽社群坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8773,
					"articleTypeName":"天府论坛网",
					"lotteryType":2
				},
				{
					"articleTypeId":8804,
					"articleTypeName":"必中四肖网",
					"lotteryType":2
				},
				{
					"articleTypeId":8563,
					"articleTypeName":"金钥匙论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":8583,
					"articleTypeName":"港澳天空彩票",
					"lotteryType":2
				},
				{
					"articleTypeId":8823,
					"articleTypeName":"鱼跃龙门网",
					"lotteryType":2
				},
				{
					"articleTypeId":8706,
					"articleTypeName":"大陆仔论坛",
					"lotteryType":2
				},
				{
					"articleTypeId":6922,
					"articleTypeName":"镇坛之宝",
					"lotteryType":2
				},
				{
					"articleTypeId":6912,
					"articleTypeName":"精选玄机",
					"lotteryType":2
				},
				{
					"articleTypeId":6932,
					"articleTypeName":"任我发料",
					"lotteryType":2
				},
				{
					"articleTypeId":6942,
					"articleTypeName":"澳门惠泽",
					"lotteryType":2
				},
				{
					"articleTypeId":6952,
					"articleTypeName":"内部资料",
					"lotteryType":2
				},
				{
					"articleTypeId":6962,
					"articleTypeName":"王牌猛料",
					"lotteryType":2
				},
				{
					"articleTypeId":6972,
					"articleTypeName":"传真内幕",
					"lotteryType":2
				},
				{
					"articleTypeId":6982,
					"articleTypeName":"彩坛至尊",
					"lotteryType":2
				},
				{
					"articleTypeId":6992,
					"articleTypeName":"十虎权威",
					"lotteryType":2
				},
				{
					"articleTypeId":7002,
					"articleTypeName":"蓝月亮料",
					"lotteryType":2
				},
				{
					"articleTypeId":7012,
					"articleTypeName":"天线宝宝",
					"lotteryType":2
				},
				{
					"articleTypeId":7022,
					"articleTypeName":"高手杀料",
					"lotteryType":2
				},
				{
					"articleTypeId":7032,
					"articleTypeName":"博发世家",
					"lotteryType":2
				},
				{
					"articleTypeId":7042,
					"articleTypeName":"特区天顺",
					"lotteryType":2
				},
				{
					"articleTypeId":7052,
					"articleTypeName":"各坛精料",
					"lotteryType":2
				},
				{
					"articleTypeId":7062,
					"articleTypeName":"凤凰马经",
					"lotteryType":2
				},
				{
					"articleTypeId":7072,
					"articleTypeName":"百万富翁",
					"lotteryType":2
				},
				{
					"articleTypeId":7082,
					"articleTypeName":"马会官方",
					"lotteryType":2
				},
				{
					"articleTypeId":7092,
					"articleTypeName":"金明世家",
					"lotteryType":2
				},
				{
					"articleTypeId":7102,
					"articleTypeName":"天下精英",
					"lotteryType":2
				},
				{
					"articleTypeId":7122,
					"articleTypeName":"18点来料",
					"lotteryType":2
				},
				{
					"articleTypeId":7232,
					"articleTypeName":"六合皇料",
					"lotteryType":2
				},
				{
					"articleTypeId":7242,
					"articleTypeName":"六合财神",
					"lotteryType":2
				},
				{
					"articleTypeId":7262,
					"articleTypeName":"固定规律",
					"lotteryType":2
				},
				{
					"articleTypeId":7272,
					"articleTypeName":"解说彩票",
					"lotteryType":2
				},
				{
					"articleTypeId":7282,
					"articleTypeName":"买码建议",
					"lotteryType":2
				},
				{
					"articleTypeId":7292,
					"articleTypeName":"彩票茶话",
					"lotteryType":2
				},
				{
					"articleTypeId":7302,
					"articleTypeName":"特碼規律",
					"lotteryType":2
				},
				{
					"articleTypeId":7312,
					"articleTypeName":"规律秘诀",
					"lotteryType":2
				},
				{
					"articleTypeId":7322,
					"articleTypeName":"澳门博彩",
					"lotteryType":2
				}
			],
}